In [6]:
import pickle
import numpy as np
import pandas as pd

In [7]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('model/clf.pkl', 'rb'))

In [8]:
# assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked

test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype= object).reshape(1, 7)

In [9]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [10]:
test_input_sex = ohe_sex.transform(pd.DataFrame(test_input[:, 1], columns=['Sex']))

In [11]:
test_input_sex

array([[0., 1.]])

In [13]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [14]:
test_input_embarked

array([[0., 0., 1.]])

In [15]:
test_input_age = test_input[:, 2].reshape(1, 1)
test_input_age

array([[31.0]], dtype=object)

In [16]:
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_age, test_input_embarked, test_input_sex), axis=1)

In [17]:
test_input_transformed.shape

(1, 10)

In [18]:
clf.predict(test_input_transformed)

array([0])